name: Auto populate PR title from branch name

on:
  pull_request:
    types: [opened]

jobs:
  auto-populate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set PR title from branch name
        run: echo "::set-input name=pull_request_title::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          pull_request_title: "ethan Test"
          base: ${{ github.head_ref }}