name: Set PR Title

on:
  pull_request:
    types: [opened]

jobs:
  set-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Title
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          title: "123"
          commit-message: Update PR Title